services:
  # Web Service
  - type: web
    name: reflexagent-web
    env: ruby
    buildCommand: render-build.sh 
    startCommand: bundle exec puma -C config/puma.rb
    healthCheckPath: /health
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        value: postgresql://reflex_agent_production_user:Dl6S9x0DT6kwCGNJXnmGbNJySh0vLlv3@dpg-d09kdure5dus73boghi0-a.frankfurt-postgres.render.com/reflex_agent_production
      - key: REDIS_URL
        fromService:
          type: redis
          name: reflexagent-redis
          property: connectionString
      - key: REDIS_POOL_SIZE
        value: 10
      - key: REDIS_TIMEOUT
        value: 5
      - key: REDIS_RECONNECT_ATTEMPTS
        value: 3
      - key: WEBHOOK_SECRET
        sync: false
    autoDeploy: true
  
  # Background Worker Service
  - type: worker
    name: reflexagent-worker
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://reflex_agent_production_user:Dl6S9x0DT6kwCGNJXnmGbNJySh0vLlv3@dpg-d09kdure5dus73boghi0-a.frankfurt-postgres.render.com/reflex_agent_production
      - key: REDIS_URL
        fromService:
          type: redis
          name: reflexagent-redis
          property: connectionString
      - key: REDIS_POOL_SIZE
        value: 15
      - key: REDIS_TIMEOUT
        value: 5
      - key: REDIS_RECONNECT_ATTEMPTS
        value: 3
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
    autoDeploy: true

# Database
databases:
  - name: reflexagent-postgres
    plan: standard
    postgresMajorVersion: 14

# Redis instance
services:
  - type: redis
    name: reflexagent-redis
    plan: standard
    maxmemoryPolicy: volatile-lru
    ipAllowList: [] # allow all connections 