# config/schedule.yml

metric_aggregation_hourly:
  cron: "5 * * * *"  # 5 minutes past every hour
  class: "MetricAggregationJob"
  args: ["hourly"]
  queue: metric_aggregation

metric_aggregation_daily:
  cron: "10 0 * * *"  # 10 minutes past midnight
  class: "MetricAggregationJob"
  args: ["daily"]
  queue: metric_aggregation