---
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5).to_i %>
:timeout: 25
:verbose: false
:queues:
  - [raw_events, 10]
  - [event_processing, 8]
  - [metric_calculation, 5]
  - [metric_aggregation, 5]
  - [anomaly_detection, 3]
  - [default, 1]

:max_retries: 3
:poll_interval_average: 15
:average_scheduled_poll_interval: 15 